$('#CollapseAll').click(function(){
    $('.matn').slideUp()
})
$('#ExpandAll').click(function(){
    $('.matn').slideDown()
})
$('#ti1').click(function(){
    $('#Item1').slideToggle()
})
$('#ti2').click(function(){
    $('#Item2').slideToggle()
})
$('#ti3').click(function(){
    $('#Item3').slideToggle()
})
$('#ti4').click(function(){
    $('#Item4').slideToggle()
})
$('#ti5').click(function(){
    $('#Item5').slideToggle()
})